### ISSUE TITLE
variantBySelectedOptions returns null 

### ISSUE THREAD

**Issue by mandarzope** [Shopify/storefront-api-examples#102]
**variantBySelectedOptions** is not returning variants despite variant exists in db
GraphQL query
`
query{

	collectionByHandle: collectionByHandle(handle: "sheet-set") {
		title
  	products(first:1){
      edges{
        node{
          options {
            id,
            name,
            values
          }
          variants(first:1){
            edges{
              node{
                priceV2{
                  amount
                }
                selectedOptions{
                  name,
                  value
                }
              }
            }
          }
          variantBySelectedOptions(selectedOptions:{
            name:"Size"
            value:"Twin"
          }
    ){
      id
    }
        }
      }
    }
	}
}
`

GraphQL response

`
{
  "data": {
    "collectionByHandle": {
      "title": "Sheet Set",
      "products": {
        "edges": [
          {
            "node": {
              "options": [
                {
                  "id": "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0T3B0aW9uLzU2MTk0MDg4OTYxMzg=",
                  "name": "Color",
                  "values": [
                    "Blush",
                    "Chocolate Brown",
                    "Red Wine",
                    "Blue",
                    "Indigo Batik",
                    "Light Grey",
                    "Vanilla",
                    "Slate Grey",
                    "Pure White",
                    "Mod Spa",
                    "Black",
                    "Green Sage",
                    "Indigo Batik Blue"
                  ]
                },
                {
                  "id": "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0T3B0aW9uLzU2MTk0MDg5Mjg5MDY=",
                  "name": "Size",
                  "values": [
                    "Twin",
                    "Twin XL",
                    "Full",
                    "Queen",
                    "King",
                    "California King"
                  ]
                },
                {
                  "id": "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0T3B0aW9uLzU2MTk0MDg5NjE2NzQ=",
                  "name": "Fabric",
                  "values": [
                    "100% Cotton"
                  ]
                }
              ],
              "variantBySelectedOptions": null
            }
          }
        ]
      }
    }
  }
}
`

**Comment by rebeccajfriedman** [comment]
@mandarzope Can you share your myshopify domain? I'd like to look into this issue, but you haven't provided enough information.

**Comment by rebeccajfriedman** [comment]
Closing this out due to lack of activity.

**Comment by mandarzope** [comment]
Apologies Rebecca for delayed response. Please find the domain http://california-design-den.myshopify.com
