### ISSUE TITLE
Unable to query checkout after it's created

### ISSUE THREAD

**Issue by dbridenbeck** [Shopify/storefront-api-examples#123]
When reading the [docs](https://shopify.dev/tutorials/create-a-checkout-with-storefront-api) it's not clear to me if it's possible to query a checkout after it's been created.

Below is my use-case, which is currently implemented with the buy-sdk. Any advice on how I could create a similar process with the Storefront API? I'm using React and Apollo for my project:

1. Create checkout on init load
2. Add/update/remove line items as needed throughout the app
3. Send user to checkout webURL to complete checkout with shopify
4. When user comes back to the site, i want to make sure the checkout was completed. If so, create a new checkout, if not, keep using existing checkout.

**Comment by swalkinshaw** [comment]
Yes it's possible to query a checkout. You can see an example in the doc link you posted under the "Setting the shipping rate" section. Use the `id` 

```graphql
query {
  node(id: "someid") {
    ... on Checkout {
      id
      webUrl
    }
  }
}
```
