### ISSUE TITLE
npm start > Module not found..

### ISSUE THREAD

**Issue by triemenschneider** [Shopify/storefront-api-examples#17]
`index.js` is referencing `../../shared/app.css`, which does not exist.

Hence `npm start` or `yarn start` throughs an error.

<img width="697" alt="bildschirmfoto 2017-06-05 um 08 02 28" src="https://cloud.githubusercontent.com/assets/3159548/26772430/a3d6d1a2-49c5-11e7-8972-bc4b56dda47a.png">

**Comment by swalkinshaw** [comment]
It looks like you only have the `react-js-buy` example and not the full repository cloned?

It will work from `storefront-api-examples/react-js-buy`

**Comment by triemenschneider** [comment]
@swalkinshaw Ah, ok. Thanks. 😬
