### ISSUE TITLE
StoreFront API status

### ISSUE THREAD

**Issue by IngenieroLata** [Shopify/storefront-api-examples#18]
Hello Everyone! I know this is probably the wrong place to discuss a couple of questions I have, but couldn't find another place. Sorry if I disturb.

I find this new StoreFront API really interesting. For a long I wanted more UX on Shopify based sites. So having this will definitly, as you said
> give you creative control to build customized purchasing experiences for your customers

But also I have some questions. 

- Will this be integrated in someway with the StoreFront Editor? as a headless CMS like [Prismic](https://prismic.io/)
- Sections like the Checkout are available for Plus accounts only, How is this gonna change?
- There are a couple of analytics really useful, pages where people come from, abandoned carts, etc. All of this things are gonna have it's own APIs?

**Comment by swalkinshaw** [comment]
> Will this be integrated in someway with the StoreFront Editor? as a headless CMS like Prismic

No plans on this as of yet.

> Sections like the Checkout are available for Plus accounts only, How is this gonna change?

Certain parts of the API require special access which can be granted to Plus accounts. That's not really changing.

> There are a couple of analytics really useful, pages where people come from, abandoned carts, etc. All of this things are gonna have it's own APIs?

Any kinds of analytics like this would be part of the Admin/Merchant API, not Storefront.
