### ISSUE TITLE
Can't create Checkout

### ISSUE THREAD

**Issue by jsvde** [Shopify/storefront-api-examples#19]
I know these examples rely on an alpha version of the shopify-buy package (^1.0.0-alpha.7) but the provided examples currently fail to create a checkout. Last week everything worked as intended.

To reproduce the issue choose `react-js-buy` for example, install dependencies and start the app.

Error in console:
`Uncaught (in promise) TypeError: Cannot read property 'checkoutCreate' of undefined
    at index.js:3129
    at <anonymous>`

an update to `^1.0.0-alpha.9` fixes the issue of cart creation but since the api slightly differs examples still don't work properly

**Comment by swalkinshaw** [comment]
> an update to ^1.0.0-alpha.9 fixes the issue of cart creation but since the api slightly differs examples still don't work properly

Do you mean that the examples which don't use shopify-buy aren't fixed? Or is something other than cart creation broken?

**Comment by jsvde** [comment]
I encountered errors on all react examples, didn't have time to check out all other examples.

**react-apollo**:
Can't create checkout(?)/add to cart. A console error for checkout creation and all cart related actions pops up with
`Uncaught (in promise) Error: GraphQL error: No operation named ""
    at new ApolloError (apollo.umd.js:1845)
    at apollo.umd.js:2538
    at <anonymous>`

**react-js-buy**:
Can't create checkout, all issues resolved when updating to `^1.0.0-alpha.9` of `shopify-buy`

**react-graphql-client**:
Can't add to cart. Debugging the graphql call yields the message: `"Nullability mismatch on variable $lineItems and argument lineItems ([CheckoutLineItemInput!] / [CheckoutLineItemInput!]!)"` on the 
`checkoutLineItemsAdd` mutation.

When running `yarn run schema:refresh` in `react-graphql-client` there is an update of the schema available. The new schema alters the `checkoutLineItemsAdd` mutation and causes errors on react-graphql-client and react-apollo.

**Comment by swalkinshaw** [comment]
@jsvde thanks so much for the details. We're aware of the bugs in the graphql-client versions since a mutation slightly changed. Those will be fixed today and we'll investigate the others too 👍

**Comment by jsvde** [comment]
You're very welcome. Thanks for the great work, I'm excited to run this in production in the future.
The issue can be closed then I guess.
