### ISSUE TITLE
PWA example using Polymer

### ISSUE THREAD

**Issue by JosefJezek** [Shopify/storefront-api-examples#22]
Could you write PWA example using Polymer elements and tools?

- https://www.polymer-project.org
- https://www.webcomponents.org
- https://github.com/Polymer/shop
- https://www.youtube.com/results?search_query=google+io+17+polymer
- https://github.com/aruntk/polymer-apollo

**Comment by rebeccajfriedman** [comment]
This repo is largely for community members to contribute examples to. If you now have a working Polymer PWA example, please consider submitting a PR!
