### ISSUE TITLE
Question: Query for linklists

### ISSUE THREAD

**Issue by ButsAndCats** [Shopify/storefront-api-examples#25]
I have checked the documentation just looking for confirmation of this.

Is it possible to query linklists using the storefront api?
Will it ever be possible?

**Comment by swalkinshaw** [comment]
What do you mean by linklists?

**Comment by ButsAndCats** [comment]
Navigation Menus, 
Something similar to the liquid object perhaps.
https://help.shopify.com/themes/liquid/objects/linklist

**Comment by swalkinshaw** [comment]
Oh Navigation menus :)

Thanks, we'll look into adding those.

**Comment by swalkinshaw** [comment]
So Navigation menus are tied to the Online Store itself since they use its URLs. When using the Storefront API you're building a custom storefront so you're in control of your routes/URLs. It makes sense to have in Liquid for themes, but not in the Storefront API.
