### ISSUE TITLE
[Question]: Selling products you don't own

### ISSUE THREAD

**Issue by jakeaaron** [Shopify/storefront-api-examples#27]
Hello,

Thanks for your examples (especially the React one!)—they are helpful!

I have a general question on how to use the shopify api to sell products that other people own.
Do you know how this would be possible?
Would I need each merchant to send me their `X-Shopify-Storefront-Access-Token`?
Is there a better way that makes it easier for merchants to sell their products through my service?

Thank you for your time!

**Comment by swalkinshaw** [comment]
Generally, you'd create a Sales Channel app which other Merchants publish their products to.

See https://developers.shopify.com/sales-channel-sdk
