### ISSUE TITLE
customerRecover, customerReset and invalid type ID!

### ISSUE THREAD

**Issue by nickdandakis** [Shopify/storefront-api-examples#31]
I'm currently implementing a password reset flow, and ran into an issue with the `customerReset` mutation. Firing `customerRecover` sends an email notification, as expected. I modified the email notification template to point to my server instead, for example http://localhost:3000/reset-password/6655363669/7c4a5966d0901b57ee96af96eddb0eb5-1503254727.

The problem is that `customerReset` takes a customer ID, which should be `6655363669` here. But from what I can tell, that's a Shopify Customer ID, but not necessarily a Shopify Storefront API Customer ID? The exact error I get is "GraphQL error: Variable id of type ID! was provided invalid value". The docs show an ID that looks like `Z2lkOi8vU2hvcGlmeS9FeGFtcGxlLzE=`, and not `6655363669`. Do I need to modify the email notification template? If so, what Liquid template variable(s) do I use to create a correct password reset URL?

An example that includes password recovery would be great, but it also just looks like that mutation is expecting the wrong arguments.

**Comment by swalkinshaw** [comment]
Yeah the Storefront API expects any field/input with the type of `ID` to be in our "Storefront" format (an encoded ID). So an integer based ID direct from Shopify admin/links don't work.

This is an interesting use case that we hadn't thought about yet or ran into. Unfortunately there's no Liquid variable/filter exposed which can do this.

We'll need to think about this 🤔

**Comment by nickdandakis** [comment]
@swalkinshaw, thank you for the quick reply.

Is there any workaround for this? The only thing I can think of is setting a temporary password for the user via the Admin API, and then forcing them to set a new password on authentication. Is there any way to derive the Storefront `ID` from the integer based one?

We're relying on the Shopify Storefront API extensively, and would love to figure this one out as soon as possible.

**Comment by swalkinshaw** [comment]
The quick workaround is to build the encoded ID yourself:

`gid://shopify/Customer/6655363669` is the format. Then you Base64 encode it.

Warning: *do not* rely on this long term. These IDs are encoded for a reason because they can change. This is just a quick fix for this.

We'll have to figure out a proper solution to this.

**Comment by swalkinshaw** [comment]
@nickdandakis can you provide more details on your custom template?

How are you generating that reset-password URL? Is that directly from a Liquid variable? Or are you using a combination of others to build it?

**Comment by nickdandakis** [comment]
So, I looked for a Liquid variable for just the reset password token and couldn't find one. `customer.reset_password_url` is used in the 'Customer account password reset' email notification template, however that's undocumented as well.

I ended up with this hack:
```
{% assign reset_password_url = customer.reset_password_url | replace: "https://token-local.myshopify.com/account/reset", "http://localhost:3000/reset-password" %}
```

Which is also fine for right now, but obviously don't want to rely on this either. [Here's a Shopify forum post I found that's related to this](https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/reset-password-token-in-notification-email-452983). 

What I'd like to have is access to Liquid variables for the Customer Storefront API ID, and the Customer Reset Password Token.

I'm assuming the `customerActivate` mutation will run into the same issue too. So might be best to also have a Liquid variable for the Customer Activation Token!

**Comment by swalkinshaw** [comment]
Well that's terrible 😄 .

Yeah our first idea is to add a liquid variable for the token and then update our mutation to directly take that instead of the customer ID. We likely don't need it since the token can identify the customer anyway.

We'll either need to create a brand new mutation like `customerResetByToken` or somehow migrate the existing in a non-breaking way.

**Comment by nickdandakis** [comment]
The liquid variable would tremendously help, for sure. 

Would making the ID an optional parameter in the existing `customerReset` mutation be the fix non-breaking fix? I'm honestly surprised that all this happened, and wonder if anyone is actually using this mutation.

**Comment by swalkinshaw** [comment]
> I'm honestly surprised that all this happened, and wonder if anyone is actually using this mutation.

We've seen about 6 queries with it in the past week and 4 were yours. There's only one way to use it properly right now and that's via a native app which can register URL handlers to open the reset link in a native app.

We can make it optional but we need to verify usage has migrated over before removing it completely.

**Comment by yekimmi** [comment]
i'm doing something similar using the Storefront API to create our own reset password page; however, when i go to submit, i'm receiving an "Invalid reset token" error. i'm using the workaround mentioned above to properly encode the customer ID for the request, but maybe i'm missing something with the reset token? the reset token i'm using is just taken from the end of the original reset password url (`.../account/reset/<user-id>/<reset-token>`).

**Comment by swalkinshaw** [comment]
@yekimmi are you referencing the [ `customerReset`](https://help.shopify.com/api/storefront-api/reference/mutation/customerreset) mutation?

It takes an `id` argument which is the "encoded" customer ID, and then a `resetToken` within `input`. The `resetToken` is just the string from that URL though. It doesn't need to be encoded (only fields with the `ID` type do).

**Comment by yekimmi** [comment]
yup, that’s exactly what i’m doing and getting the invalid reset token error. the user-id from the path i posted i’m encoding and using as the id and the reset-token from the path i’m using as-is as the resetToken in the input.

**Comment by swalkinshaw** [comment]
cc @Shopify/storefront-api we'll have to verify behaviour of this mutation

**Comment by osadchuk** [comment]
Hi @swalkinshaw, just wondering if there's been any development on this - is building the encoded ID manually is still the required workaround?

**Comment by swalkinshaw** [comment]
The workaround is still required but it's been added to our roadmap recently.

**Comment by osadchuk** [comment]
Thanks for the update, @swalkinshaw!

**Comment by arobbins** [comment]
Hey @swalkinshaw 

Has there been any progress on this? I'm running into the same issue in my app as well.

**Comment by swalkinshaw** [comment]
We added a new [`customerResetByUrl`](https://help.shopify.com/en/api/storefront-api/reference/mutation/customerresetbyurl) mutation about a year ago to fix this issue. It takes the reset password url to make it easier on clients and get around this ID issue.

I guess this issue should have been closed so I'll do that now 😄

**Comment by arobbins** [comment]
@swalkinshaw Thank you! Quick question if you have time. 

Where do I find the `resetUrl` for the `customerResetByUrl` mutation? Am I simply passing in the URL of my custom storefront page? Then this gets set to the "reset password link" emailed to the user?

I guess I'm confused because the description for the above mutation says the URL comes from `CustomerRecover` but it looks like the latter only returns `customerUserErrors`?

I'm probably missing something obvious here :)

**Comment by arobbins** [comment]
Ok I finally figured out that `customerResetByUrl ` takes the default Shopify password reset URL. This is the same URL set within the password reset email template.

Is `customerResetByUrl ` intended to be used programmatically? I'm trying to build the password reset flow on my own site without the user going to Shopify. So ideally, I'm trying to force the password reset link to point to my own server without modifying the email template.

But it seems I have no way of fetching the `resetUrl` via the API. The only place I see `resetUrl` is within the password reset email.

Any direction would be much appreciated!

**Comment by rebeccajfriedman** [comment]
Unfortunately, it can't be used programmatically at this time. We already have this concern on our radar and will update on this ticket once we've addressed it.

**Comment by arobbins** [comment]
Thanks for the update!

**Comment by karltaylor** [comment]
So if I am following correctly, the only way to do a full password reset flow with storefront api is to:

- Call [`customerRecover`](https://shopify.dev/api/storefront/reference/customers/customerrecover) mutation

And either:

- Pass the default Shopify password reset url generated in the email, in to the link to your app (via query params?)
- Use the default Shopify url in [`customerResetByUrl`](https://shopify.dev/api/storefront/reference/customers/customerresetbyurl)

Or

- build the encoded ID and base64 Encode it and then use that in [`customerReset`](https://shopify.dev/api/storefront/reference/customers/customerreset)

Is that correct? And `customerResetByUrl` is the preferred method?

**Comment by swalkinshaw** [comment]
> Is that correct? And customerResetByUrl is the preferred method?

Yes it is. There's a similar question on our forums with more details: https://community.shopify.com/c/Shopify-APIs-and-SDKs/Storefront-API-Help-using-customerResetByUrl-mutations/td-p/556812
