### ISSUE TITLE
Unknown field `productTypes` on type `Shop`

### ISSUE THREAD

**Issue by FrankenSteinxD** [Shopify/storefront-api-examples#33]
Hello.
I got the schema from the examples here.
I want to get product types in my application, I tried the query on graphql-explorer in the website
and it worked fine.
so is my schema old ? or I can't get product types.
btw, where to download the schema from ?
I couldn't find any link to it in the api reference so I got it from here.

**Comment by swalkinshaw** [comment]
Yeah the schemas in this repo are out of date.

You can always get the latest schema from the server via the standard GraphQL introspection query. You can use a tool like https://github.com/Shopify/graphql-js-schema-fetch to make it easier. 

Once you update your schema, `productType` should be available.
