### ISSUE TITLE
Angular example

### ISSUE THREAD

**Issue by JsssCode** [Shopify/storefront-api-examples#34]
I have developed Angular 4 Storefront API example https://github.com/JsssCode/SmallAwesomeShop.
Maybe it would be helpful to someone. 
Looking forward to adding it to this repo!

**Comment by magic-77** [comment]
@JsssCode Hi, thanks for this example App. It is useful for me, because i'm developing an Shopify App using Ionic 3.
Do you know how to implement a Customer Login Page?

**Comment by JsssCode** [comment]
@magic-77 Great that it helps you. No, I didn't work on this

**Comment by magic-77** [comment]
@JsssCode Hi, i refactored my app, now using Storefront API + Admin API. This works much better

**Comment by ribalnasr** [comment]
@magic-77 can you please show how you got the admin api to work. for now i'm struggling with types.ts, how can i generate that file for the admin client?

**Comment by magic-77** [comment]
@ribalnasr You can fetch it this way:
```
graphql-js-schema-fetch --url 'https://xxx:yyy@<your-shop-name>.myshopify.com/admin/api/graphql.json' | jq '.' > schema.json
```
To get the right URL for https://xxx:yyy@<your-shop-name>, login to Admin and copy it from the Field "Example url"

**Comment by ribalnasr** [comment]
@magic-77 can you stay with me on this one please, am extremely new to graphql.

this line does not work:
`$ graphql-js-schema-fetch --url 'https://apikey:password@<your-shop-name>.myshopify.com/admin/api/graphql.json' | jq '.' > schema.json`

**Error: Cannot find module 'commander'**

when i try to run it without `| jq '.'` it works and creates the file schema.json.

however i believe what am looking for is a .ts file like this one
https://github.com/JsssCode/SmallAwesomeShop/blob/master/src/app/shared/services/types.ts
correct?

**Comment by magic-77** [comment]
You have to convert json schema to types like this
    graphql-js-schema --schema-file schema.json --outdir ./src --schema-bundle-name 'Types' --bundle-only

**Comment by sutkovoy** [comment]
Thanks for example

**Comment by swalkinshaw** [comment]
Closing since the Angular example has been merged.

**Comment by Dharma-DX** [comment]
@JsssCode  your angular 4 code is helpfull for me , 
i stucked in CORS issue for Shopify REST API Post Method for add Product. now to try to use proxy ,if any one faced the same issue please help me.
Thanks.

**Comment by JsssCode** [comment]
@Dharma-DX I didn't face CORS problem for Shopify, but you could try to run Chrome without CORS, like described here https://alfilatov.com/posts/run-chrome-without-cors/
