### ISSUE TITLE
GraphQL error: CustomerAccessTokenRenew access denied

### ISSUE THREAD

**Issue by nickdandakis** [Shopify/storefront-api-examples#36]
We're starting to experience a critical bug with our `customerAccessToken` renewal logic. It looks like the `customerAccessTokenRenew` mutation is running into permission issues. There's nothing in the [documentation](https://help.shopify.com/api/storefront-api/reference/mutation/customeraccesstokenrenew) that implies special permissions required for this mutation.

Any help would be greatly appreciated @swalkinshaw. It's only a matter of time before this starts to affect our customers, since their access tokens are bound to expire soon.

**Comment by swalkinshaw** [comment]
I just tested `customerAccessTokenRenew` and it seems to be working as expected. 
That mutation requires the `unauthenticated_write_customers` permission.

Can you confirm how you got access to the API? Did you create a private app and use the credentials from there?

**Comment by nickdandakis** [comment]
Yeah, created a private app and used the Storefront API access token from there.

I don't see any way of setting a `unauthenticated_write_customers` permission in the private app settings view.

**Comment by minasmart** [comment]
Are you using this in a front-end web or mobile application? Or are you persisting these tokens on a server somewhere?

Can you show us the request and response? Maybe give us some info on your shop? How long have you been renewing the tokens?

If you're not comfortable sharing shop details here, please email Scott and I at scott.walkinshaw@shopify.com and mina.smart@shopify.com

**Comment by swalkinshaw** [comment]
Are you getting an "access denied" error? That could also mean two other things:

1. the access token provided isn't valid for the app you auth'd with
2. the token is already expired

Unfortunately the error messages in this case aren't too useful since it could be a few things.

`unauthenticated_write_customers` is automatically provided right now when you create a private app, we can verify that though so see @minasmart's reply :)

**Comment by nickdandakis** [comment]
@minasmart, front-end web application (https://token.ai). We're persisting the tokens in a Firebase realtime database. The shop has been up for just over a month. @swalkinshaw, we renew the tokens _after_ they expire. Is that not how this endpoint is intended to be used?

Thank you for dropping your emails. I'd like to resolve this in public view as much as possible, since I'm sure it's helpful information for anyone that uses this API.

**Comment by nickdandakis** [comment]
We've had some users register to our production Shopify store two months ago, hence the expired tokens that aren't getting renewed properly. We used the standard Shopify web store sales channel for that. About a month later, we launched the current storefront that uses the Storefront API.

**Comment by swalkinshaw** [comment]
> Is that not how this endpoint is intended to be used?

I can definitely see how this is confusing now 😖 

But no, they need to be renewed *before* they expire. The alternative now is creating new access tokens.

**Comment by nickdandakis** [comment]
Ah gotcha. Seems a little weird to have a renewal mutation that only works with valid tokens. We're going to refactor our code to create a new token if expired, and never renew.

Thanks for the prompt replies!

**Comment by swalkinshaw** [comment]
Thanks for bringing this up though. Two improvements will likely come from it:

* better description for this mutation
* better error messages instead of just "access denied"
