### ISSUE TITLE
Sort products by price

### ISSUE THREAD

**Issue by lloydstubber** [Shopify/storefront-api-examples#37]
I'm using the Storefront API with Vue to pull in all products and then sort by price. From what I've read this cannot by done straight from products, you need to query the collectionsByHandle for the collection, then access products.

Unfortunately I'm not having much luck with this below. I have that collection available and accessible via the Storefront API but it's not retrieving it. The documentation for this is quite scarce so any help would be muchly appreciated!

```
      {
        shop {
          collectionByHandle(handle: "all-products") {
            products(sortKey: PRICE) {
              edges {
                node {
                  id
                  title
                  onlineStoreUrl
                  productType
                  images (first: 1, maxWidth: 300, maxHeight: 300, crop: CENTER) {
                    edges {
                      node {
                        src
                        altText
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
```

For clarification, this query below pulls in products when just querying products(first: 20) but it seems there is no sortKey for price when looking at only products. So after using the GraphQL Explorer I've seen you need to do via collectionsByHandle first, then drill down to products. Please correct me if I'm wrong...

```
      {
        shop {
          name
          products(first: 20) {
            edges {
              node {
                id
                title
                onlineStoreUrl
                productType
                images (first: 1, maxWidth: 300, maxHeight: 300, crop: CENTER) {
                  edges {
                    node {
                      src
                      altText
                    }
                  }
                }
              }
            }
          }
        }
      }
```

**Comment by swalkinshaw** [comment]
You're correct that right now you can only sort products by price *within* a collection. This seems kind of weird though now that I think about it and maybe we can add `PRICE` as an option to the `ProductSortKeys`.

But your initial query should work fine. Both that collection and those products need to be published to the app/channel that you're authenticating with though.

I tried a similar query on a test shop and it works correctly and sorts by price.

**Comment by adamjseitz** [comment]
Hi @swalkinshaw

Any further thoughts on whether `PRICE` can be added to `ProductSortKeys`? It is inconvenient that it exists in the collection but not globally.
