### ISSUE TITLE
product review data in graphql

### ISSUE THREAD

**Issue by ddddave** [Shopify/storefront-api-examples#40]
Hi, I would like to access product review data through GraphQL, but working with Shopify apps does not seem like it is supported. Here is the specific app for your reference:  https://apps.shopify.com/product-reviews

Thanks

**Comment by swalkinshaw** [comment]
That's correct. Our APIs don't include data from 3rd party apps. It would be up to each app to supply their own API.

**Comment by ahsanihsan** [comment]
Hi, @davegariepy  I know it's been a long time. But were you able to find any App that could help me with this issue? I am unable to get the reviews for my product. 

https://community.shopify.com/c/Shopify-APIs-SDKs/Product-Review-API-Endpoint-to-add-update-reviews/td-p/482214

i even tried to use the above scenario but it gives me an HTML of the forms with classes which is not helpful because I need the data on my mobile application.

**Comment by Cam** [comment]
@davegariepy @ahsanihsan As far as I can see this would be quite possible. The 'Product Reviews' app stores reviews in product metafields, which you can access using the [Storefront API](https://help.shopify.com/en/api/storefront-api/reference/object/metafield).

You wouldn't be able to update the reviews. But could fetch them.

**Comment by ahsanihsan** [comment]
@Cam I came across that but the thing is that I am trying to integrate the reviews on mobile end. So for that I would need to update or create a review which is not being offered by the Store Front API.

**Comment by Cam** [comment]
@ahsanihsan Ahh. In that case, the right approach would probably be to roll your own review features, or to use a review platform that has agnostic embeddable UIs or an API.

**Comment by ahsanihsan** [comment]
@Cam I was thinking the same tbvh 😅 But is there any application in Shopify Store that could help me in such case. Else I would introduce them in an API.

**Comment by Cam** [comment]
@ahsanihsan either way you are going to need to use some kind of API, as the Storefront API is for Shopify, not other applications.

**Comment by ahsanihsan** [comment]
@Cam Okay I get it. Thank you so much for your help.

**Comment by adamjw3** [comment]
What did you do to solve the creating a new review? I'm porting a liquid store to a js sdk store and want to keep
Reviews and the form on the product page. Any help
