### ISSUE TITLE
Shopify API POST request not working with POSTMAN on Private Apps

### ISSUE THREAD

**Issue by nikhilgangwal** [Shopify/storefront-api-examples#41]
I'm trying to make a very basic POST request for a private shopify app. I am working with Postman REST client EXACTLY as described here:
https://help.shopify.com/api/tutorials/using-postman
Unfortunately, It is not working. It returns status 200 and return an html page that says : "Log in to manage your store".
It does not apply any changes to the shop.
For some reason, GET requests work fine while all POST requests fail.

I am currently using the trial account of 14 days. So is it the issue with trial account?

**Comment by swalkinshaw** [comment]
This repo is for our Storefront GraphQL API, not REST. Support can be found here at https://developers.shopify.com/community
