### ISSUE TITLE
Can't able to do login through the Shopify api from my ionic app

### ISSUE THREAD

**Issue by sanju1993** [Shopify/storefront-api-examples#43]
I have been searching for customer  login Api for Ionic , but I haven't seen a good answer.
I need to let the customer to login from my ionic app using Shopify api. so can you please guide me 
How can i do the login part..?

**Comment by swalkinshaw** [comment]
Our react-apollo example has customer logic. It's code may help you: https://github.com/Shopify/storefront-api-examples/blob/master/react-apollo/src/components/CustomerAuth.js
