### ISSUE TITLE
mutation  customerAccessTokenCreate : Doesn't  work on ionic 3

### ISSUE THREAD

**Issue by sanju1993** [Shopify/storefront-api-examples#44]
hello 
i am trying to do login in my Ionic 3 app using my shopify store  (hectic by natalia) customer,  but I haven't seen a good answer. and i also attempt : 

```graphql
mutation customerAccessTokenCreate($input: CustomerAccessTokenCreateInput!) {
  customerAccessTokenCreate(input: $input) {
    userErrors {
      field
      message
    }
    customerAccessToken {
      accessToken
      expiresAt
    }
  }
}
```

but these syntax doesn't work on Ionic or may be i am doing something wrong , so if you have any suggestions regarding this , which is allow to do in ionic3 please guide me !

Thanks

**Comment by swalkinshaw** [comment]
This isn't the place for support, but you can find documentation for that mutation here: https://help.shopify.com/api/storefront-api/reference/mutation/customeraccesstokencreate.

If you're using the `$input` variable, you need to send that as well as shown in the docs above.
