### ISSUE TITLE
Trying to access the storefront endpoints with tokens generated by the shopify admin api

### ISSUE THREAD

**Issue by benbonnet** [Shopify/storefront-api-examples#45]
We're running the storefront without problem with manually created storefront access tokens

Now in the scope of a public app, for a given install, we're creating a storefront token on the behalf of the user/store (via the shopify_api gem, `ShopifyAPI::StorefrontAccessToken.create(...etc)`)

The very same storefront developments does not work with the tokens created like so. Is that normal ? or is something missing ? I'm kind of wondering what's the use of having access to the StorefrontAccessToken via the admin api

Thx if any enlightments

**Comment by minasmart** [comment]
I'm not sure what you mean by not working. Is it returning a specific error? 

What access scopes are you providing on token creation? The full list of available scopes is listed here: https://help.shopify.com/api/reference/storefrontaccesstoken. Does the parent API client have the authenticated version of the requested scopes?

**Comment by benbonnet** [comment]
I had checked the page you've linked, added all those. Once the user installs the app, the storefront token creation happens and if I list it, those storefront tokens do have the same scopes as the oauth setup

The error received is some "an error occured" html page, instead of a graphql response
Really feels like there's something buggy, but I could be wrong

**Comment by minasmart** [comment]
Can you share the shop name or the request you’re making?

**Comment by benbonnet** [comment]
query ($handle: String!){
      shop {
        collectionByHandle(handle: $handle){
          id
          title
          products (first: 100, sortKey: MANUAL){
            edges {
              node {
                id
                title
              }
            }
          }
        }
      }
    }

**Comment by benbonnet** [comment]
@minasmart may I ask you if you've got any feedback from this ?

**Comment by markdavies** [comment]
I see the same thing here. If I use a token generated by the Admin API, I get HTML returned and a 500 status. HTML looks like this:

<img width="753" alt="screen shot 2018-04-06 at 4 04 12 pm" src="https://user-images.githubusercontent.com/320683/38405638-2accda88-39b4-11e8-9ab8-8c7438961a94.png">

The store is in development mode. I have requested the correct unauthenticated_* scopes. Also I made my add a sales channel, I saw that was required too somewhere.

I was following this guide:
https://help.shopify.com/api/storefront-api/getting-started

**Comment by swalkinshaw** [comment]
@markdavies I looked into this and found out what's going on. The Storefront API can only be used in the context of a sales channel app. The app you're using to authenticate with on the Admin API to create these tokens isn't a channel.

Looking at our docs, I can see we're missing this requirement 😞. I'll try and get those updated. In the meantime, you can follow the private app method instead. It automatically creates the private app as a channel so it will work.

@benbonnet this likely applies to you as well.

**Comment by markdavies** [comment]
@swalkinshaw - actually you're right, it works as a sales channel. I must have been using an old token. Thanks for the info!

**Comment by Rathnakreeswaran** [comment]
@swalkinshaw i have installed shopify python app(using flask framework) in shopify admin panel.after that , how to integrate the app with store front end? kindly share your thoughs or info regarding this to continue further?
