### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by TheoMer** [Shopify/storefront-api-examples#49]
OS: Windows 10 Pro
GIT: 2.8.1.windows.1

So, issuing:

```
git clone git@github.com:Shopify/storefront-api-examples.git
```

generated the following error:

```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I resolved the issue by issuing the following instead:

```
git clone https://github.com/Shopify/storefront-api-examples.git
```

**Comment by jared-fraser** [comment]
@TheoMer this sounds like an issue with your ssh keys and not this repo.

Read through https://help.github.com/articles/testing-your-ssh-connection/#platform-windows

I was successfully able to clone the repo using ssh

```
➜ git clone git@github.com:Shopify/storefront-api-examples.git
Cloning into 'storefront-api-examples'...
remote: Counting objects: 1674, done.
remote: Total 1674 (delta 0), reused 0 (delta 0), pack-reused 1674
Receiving objects: 100% (1674/1674), 1.55 MiB | 451.00 KiB/s, done.
Resolving deltas: 100% (1037/1037), done.```

**Comment by swalkinshaw** [comment]
All the instructions in this repo say to clone using `https` anyway so a key/GH account isn't required by default.
