### ISSUE TITLE
`variantBySelectedOptions` Not working as intended?

### ISSUE THREAD

**Issue by rileybracken** [Shopify/storefront-api-examples#51]
We are running this Query:
```
{
  node(id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzIyMzg2NjA2MTA1") {
    ... on Product{
      title
      handle
      variantBySelectedOptions(selectedOptions: [{ name:"Region", value:"NA"}]) {
        id
      }
    }
  }
}
```

And getting null back on the variant, even though we know that a product exists, what are we doing wrong?

**Comment by swalkinshaw** [comment]
The product might exist, but you need to be sure that a variant's option exists with those values. Note that *all* a variant's options must be match. You can't just match on a single option.

You could do the following query to verify that:

```graphql
{
  node(id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzIyMzg2NjA2MTA1") {
    ... on Product {
      title
      handle
      variants(first: 100) {
        edges {
          node {
            selectedOptions {
              name
              value
            }
          }
        }
      }
    }
  }
}
```

**Comment by rileybracken** [comment]
> Note that all a variant's options must match

This was my problem. I was hoping to get all variants that matched one option. For example you see all the time in stores where you have a blue and a red item, but they show up as 2 different products.

So something like I want all of these toy trucks in red. But then I can still select the variants of size.

**Comment by nidhi125** [comment]
Hi, same here. Is there any got solution?

**Comment by f3ltron** [comment]
nothing is working .... Maybe it's time to re open and fix this problem ?


```
{
  collectionByHandle(handle: "women-sale-dresses") {
    title
    products(first: 1) {
      edges {
        node {
          title
          options {
            id
            name
            values
          }
          variantBySelectedOptions(selectedOptions: [
            {name: "Color", value: "G178"}]) {
            title
            product {
              id
              title
            }
          }
        }
      }
    }
  }
}
```

```
{
  "data": {
    "collectionByHandle": {
      "title": "Women's Sale Dresses",
      "products": {
        "edges": [
          {
            "node": {
              "title": "BASIA DRESS",
              "options": [
                {
                  "id": "i hide the id",
                  "name": "Size",
                  "values": [
                    "L",
                    "M",
                    "S",
                    "XL",
                    "XS"
                  ]
                },
                {
                  "id": "i hide the id",
                  "name": "Color",
                  "values": [
                    "G178",
                    "N101",
                    "P424"
                  ]
                }
              ],
              "variantBySelectedOptions": null
            }
          }
        ]
      }
    }
  }
}
```

**Comment by nickvonh** [comment]
It appears that the order you list the options in affects the outcome of the query.

for instance this returns `null`

```
variantBySelectedOptions(selectedOptions:[
    {name:"Size", value: "S"},
    {name:"Color", value:"black"}
])
```

while this returns a proper result

```
variantBySelectedOptions(selectedOptions:[
    {name:"Color", value:"black"},
    {name:"Size", value: "S"}
])
```

This issue should definitely be reopened.

**Comment by f3ltron** [comment]
We changed the manner of doing this things. I think shopify he is not enough modular for more specific needs. So we decide to just use shopify to take product id prive and quantity and just push the product for the search into algolia ourselves. Because the algolia plugins in shopify is not enough modular too

**Comment by rebeccajfriedman** [comment]
I'm going to reopen this issue so that we look into the issue with ordering that @nickvonh mentioned above.

**Comment by rebeccajfriedman** [comment]
We've resolved the issue with ordering as described above. Thank you for reporting it.
