### ISSUE TITLE
git clone instructions fail

### ISSUE THREAD

**Issue by MisinformedDNA** [Shopify/storefront-api-examples#57]
The instructions say to use the following command to clone the repo:

`git clone git@github.com:Shopify/storefront-api-examples.git`

At least on Windows, this call fails

> D:\Repos>git clone git@github.com:Shopify/storefront-api-examples.git
> Cloning into 'storefront-api-examples'...
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> 

I think this is the universal way of doing it (and certainly the one recommended by GitHub): `git clone https://github.com/Shopify/storefront-api-examples.git`

**Comment by minasmart** [comment]
This is likely your git setup. Check out [this doc](https://help.github.com/articles/error-permission-denied-publickey/#platform-windows)

**Comment by MisinformedDNA** [comment]
That doc assumes that I want to be authenticated to GitHub. Authentication should not and is not required to pull a public repo.

The tutorial should either include a step for authentication to GitHub or instead use the anonymous Git call as [recommended by GitHub](https://help.github.com/articles/cloning-a-repository/).

**Comment by swalkinshaw** [comment]
Feel free to open a PR to change this. I agree it's fine to change in this case 👍
