### ISSUE TITLE
ember-apollo places real money orders

### ISSUE THREAD

**Issue by moezzie** [Shopify/storefront-api-examples#60]
I was just trying the ember-apollo out.

I set it up locally on my machine and went through the checkout process to see how it works.
By the end of it I was very surprised to see that I had actually ordered a pair of boots for 190CAD.
The money was transferred out of my bank account.

Can we put the API or payment integration into some kind of sandbox/test mode by default?

Cheers

**Comment by minasmart** [comment]
The payment integration is on test mode, but the paypal gateway got added at some point. It's been disabled. Sorry this happened, but it looks like the funds have been returned.
