### ISSUE TITLE
Query param on Collection products

### ISSUE THREAD

**Issue by thomashegge** [Shopify/storefront-api-examples#66]
It seems its not possible to use the **query** param on products array when fetching a collection. Is there a reason for this?

```
{
  shop{
    collections(first:10){
      edges{
        node{
          products(first: 10, query:"tag:'something'"){
            edges{
              node{
                title
              }
            }
          }
        }
      }
    }
  }
}
```
results in

```
{
  "errors": [
    {
      "message": "Field 'products' doesn't accept argument 'query'",
      "locations": [
        {
          "line": 22,
          "column": 31
        }
      ],
      "fields": [
        "query",
        "shop",
        "collections",
        "edges",
        "node",
        "products",
        "query"
      ]
    }
  ]
}
```

Our store, as most Shopify stores, are made up of small to very large collections. I'm not sure how else I can filter a collection's products by tags?

Any help is appreciated

Thank you,
Thomas

**Comment by PayalDinc** [comment]
@swalkinshaw  now is it supported? Please let me know.

**Comment by swalkinshaw** [comment]
Sorry it's still not supported and unlikely to be in the near future.

See https://help.shopify.com/en/api/custom-storefronts/storefront-api/reference/object/collection for the official reference.

**Comment by cupelapps** [comment]
@swalkinshaw Is it now supported? Please let me know.
Thanks
Muthu
Cupel Apps

**Comment by Hanousi** [comment]
@swalkinshaw What is the alternative to filtering products in a collection? I'm currently having to pull all products from the collection and filter them manually... This seems like a huge oversight.
