### ISSUE TITLE
Choosing between react-apollo, react-js-buy and react-graphql-client?

### ISSUE THREAD

**Issue by lapidus** [Shopify/storefront-api-examples#68]
Would be excellent with a note / documentation on the pros & cons of each approach.

I am starting out a new universal React Frontend (using NextJS) based on my Shopify backend. Which of the above would be a good fit and why?

ps. Looking for consultant to help me build this out. Please dm: daniel@lapidus.se

**Comment by zomars** [comment]
IMHO Apollo has been the one that made more sense for me. Because of the GraphQL nature of the Shopify API. But overall I think it's more a personal preference and to stick with what you're comfortable with.

**Comment by minasmart** [comment]
Yeah, this is totally a personal preference thing. There are many opinions and diverse applications. I don't see it as the role of this repo to recommend X vs Y for jus frameworks.
