### ISSUE TITLE
How can I redirect the response from Shopify to my app?

### ISSUE THREAD

**Issue by jesualdo13** [Shopify/storefront-api-examples#69]
I want to show an answer view so that the user knows that his transaction was completed, but I do not want to see it in the shopify tab, but in my app.

Thank you.

**Comment by swalkinshaw** [comment]
Sorry for the late reply. I'm guessing you mean redirect after the checkout is complete?

If so, that's beyond the scope of the Storefront API. Maybe try https://help.shopify.com/en/manual/orders/status-tracking/customize-status-tracking#add-additional-scripts
