### ISSUE TITLE
checkoutCompleteWithCreditCard Payment Gateway is Invalid

### ISSUE THREAD

**Issue by pmironov** [Shopify/storefront-api-examples#70]
Hi 

 I am creating the reactjs app. I set the shipping address and email, vault the card (receive what looks like a valid vaultD), but always get "Payment gateway is invalid" response after calling checkoutCompleteWithCreditCard mutation.
**But.** If I use Postman to vault the same credit card (perform POST request to the vault URL), I receive the token that looks the same. And I am able to complete the payment.
My gateway is (for testing) Bogus Gateway and I'm setting the card number to "1".

Could you please advise on what am I doing wrong?

**Comment by pmironov** [comment]
Closing this as we have found a solution.

**Comment by mythLabs** [comment]
Hi, pmironov.
I am having the same issue. can you share the request format you are using to send the credit card data?

**Comment by juiceboxjoe** [comment]
@pmironov can you please share your insights on this? Were there wrong/incorrect/missing parameters in your req for vaulting the credit card or your req for completing the order? Can you please share the resulting request?

@mythLabs did you get to solve this issue? Can you post your solution?

**Comment by pmironov** [comment]
@juiceboxjoe yes, there were some incorrect params in the vault request. You need to generate unique_token before vaulting and then use that same key when you process payment in the idempotencyKey param.

**Comment by juiceboxjoe** [comment]
@pmironov thanks for the response. appreciated.

**Comment by juiceboxjoe** [comment]
Fixed it. I had an error in the query string I was sending over to the vaulting endpoint..
