### ISSUE TITLE
GraphQL error: metafields doesn't exist on type 'Product'

### ISSUE THREAD

**Issue by lapidus** [Shopify/storefront-api-examples#73]
How can I retrieve metafields for a product using the Storefront API?

**Comment by rebeccajfriedman** [comment]
Metafields are not exposed though the storefront API. You'll need to supplement your functionality with the admin API, if you'd like to take advantage of them.

**Comment by damassi** [comment]
> Because they contain a mix of public and private data and there’s no way to differentiate. Were they exposed, wed be sharing possibly private data on many shops.

It would be nice if this was added to the Storefront API docs.

**Comment by asiraky** [comment]
I know this post is old, but for people coming through later, you can access metafields if you whitelist them. See [here](https://shopify.dev/tutorials/retrieve-metafields-with-storefront-api)
