### ISSUE TITLE
Storefront API Mutation Limitations

### ISSUE THREAD

**Issue by gil--** [Shopify/storefront-api-examples#77]
Hi - I'm working on a [Shopify PWA](https://github.com/gil--/gatsby-starter-shopifypwa) and have been working through adding a number of customer mutations and have a couple questions:

- How to allow a customer/user to “decline invitation” when following a customer activation email? OOB Shopify has a decline invitation when following the activate link in an email. I don't see any mutation or inputs for active mutation to allow for this functionality:

<img width="367" alt="screen shot 2018-10-04 at 8 21 42 pm" src="https://user-images.githubusercontent.com/3484527/46509837-1eb65600-c813-11e8-9691-22a7291c2f52.png">

- Why do a number of customer mutations still use userErrors while customerCreate deprecated userErrors and uses customerUserErrors? https://help.shopify.com/en/api/custom-storefronts/storefront-api/reference/mutation/customercreate#deprecated-return-fields vs https://help.shopify.com/en/api/custom-storefronts/storefront-api/reference/mutation/customerreset

- Is there any documentation on the expected data for form input? Such as length of password, password characters, etc. Those sorts of requirements that we could add to our client-side validation.

- Is it possible to use a checkout mutation to checkout with Apple Pay or go directly to a specific payment gateway? such as https://help.shopify.com/en/themes/customization/cart/add-more-checkout-buttons-to-cart-page but through the api?

**Comment by swalkinshaw** [comment]
👋 

1. Pretty sure we don't offer that feature yet. I'll note your feature request.
2. We're actively working on updating the rest of them.
3. Unfortunately no... but that would be nice. Right now you'd have to rely on the messages from `userErrors`.
4. This is a feature available to native mobile apps or for approved sales channels.

**Comment by rebeccajfriedman** [comment]
For #1: The activation token has an expiry on it, so it's not actually necessary to actively decline it. If you can provide a valid use case, I'm happy to consider it for the future.

**Comment by gil--** [comment]
@rebeccajfriedman @swalkinshaw 

Thank you both for responding to my API questions!

> This is a feature available to native mobile apps or for approved sales channels.

Would your team ever consider allowing for us to pass a parameter such as gatewayCode into the request and getting back a checkoutUrl that directly opened that gateway (if gateway code was installed on that particular store such as Paypal or Apple Pay). 

Dynamic checkout buttons is a great addition to Shopify and definitely makes having a full store via API less enticing when you can't "buy now" with one click like in a standard experience.

> If you can provide a valid use case, I'm happy to consider it for the future.

I honestly don't know of a valid use case at the moment. I was mostly trying to get to feature parity with native themes (or as close as possible within the limitation of the API) and came across that functionality. 👍 


Thanks again!
