### ISSUE TITLE
Definitive Answer on Checkout Login

### ISSUE THREAD

**Issue by gil--** [Shopify/storefront-api-examples#80]
I've spent the last couple hours researching if there's any way to utilize the storefront api and avoid having the customer log in on Shopify checkout (when coming from an authenticated session from our headless Shopify app). And it seems **No** but I can't find a definitive answer in the docs or online...

- Just saw the storefront announcements and saw "Allow customer to login automatically via X-Shopify-Customer-Access-Token header in web checkout" on https://ecommerce.shopify.com/c/api-announcements/t/stay-up-to-date-with-the-storefront-api-changes-548257 but (afaik) you can't send headers when redirecting a user to a url, this is not possible outside of mobilesdk. According to Scott @ https://github.com/Shopify/js-buy-sdk/issues/561#issuecomment-421013281 it's not currently possible except with MultiPass.

- I came across https://github.com/Shopify/js-buy-sdk/issues/430#issuecomment-333555480 which seemed to suggest we can simply pass `customer_access_token` in the webUrl but that does not seem to work a year later (if it ever worked at all) after associating the checkout with the same customerToken.

Nowhere on https://help.shopify.com/en/api/custom-storefronts/storefront-api/reference/mutation/checkoutcustomerassociatev2 or the storefront api docs does it go over authentication for checkout and that it's not possible. If it's indeed not possible to avoid making the user relogin on Shopify checkout, **can we please add a note to the official docs**? Would save me and others countless hrs sifting through Github issues and the community forum to find out the answer regarding avoiding logging in when coming to checkout screen. 

**edit**:

Perhaps we can load checkout into an iframe with the `X-Shopify-Customer-Access-Token` header via ajax XHR.

I understand the security implications (re: https://github.com/Shopify/js-buy-sdk/issues/561#issuecomment-420756486) but it's still unfortunate nonetheless. Definitely not an ideal UX and would probably lead to conversion loss but I'm not really sure how to avoid from a security/technical standpoint.

**Comment by rebeccajfriedman** [comment]
For the Storefront API, customer login on Shopify checkout is currently not supported, except through the header (via a mobile app). We are planning on adding support for [Multipass](https://help.shopify.com/en/api/reference/plus/multipass), but please note that this is only available to Plus merchants.

I have added an issue to our backlog to update the [checkout guide](https://help.shopify.com/en/api/custom-storefronts/storefront-api/guides/checkout-guide) with more explicit information regarding this.

**Comment by gil--** [comment]
Thanks Rebecca! Appreciate the response. Having more explicit info in the guide will be much appreciated. Looking forward to the Multipass support for Plus clients.

**Comment by SylarRuby** [comment]
I’ve just realised that we can associate a shipping address to a checkout. Oh man. Not sure how I’ve missed that. That way the customer has no need to log in again as they’ll see their email address and shipping already prefilled. Awesome!

**Comment by 8eecf0d2** [comment]
Just want to bump this and confirm that there is still no (documented) Storefront API method to auto-login customers to the Shopify Checkout.

**Multipass** has been released and works as described but is not a part of the Storefront API and trying to achieve different goals.

There is a Storefront API mutation called [checkoutCustomerAssociateV2](https://shopify.dev/docs/storefront-api/reference/mutation/checkoutcustomerassociatev2) but unfortunately it only appears to set the `checkout.email` property to that of the customer - _which I suppose does technically meet the criteria of assigning the checkout to a customer._

FWIW the removal of the `customer_access_token` query parameter would suggest that there is no Storefront API solution possible that would meet the security requirements (as they would all be effectively no more secure than a query parameter.)

The main reason this feature is important is it would remove the need for any server side logic (eg, Multipass) - however I'd assume the majority of merchants opting for custom storefronts probably don't see this as a big value add and already have server side logic.

@rebeccajfriedman is there any update on this feature coming to the Storefront API?

**Comment by drinkmorewaters** [comment]
Dealing with your undocumented SDK's, poor implementations and half baked methodology is a real pain. Not a day goes passed where we hit "Wait you can't do that?".......

**Comment by JoeyFenny** [comment]
**Just give us a query parameter.**

"Well, what if someone had access to the customer's accessToken? They could perform actions on behalf of the customer."

...

Well, what if someone had access to the customers login information? They could perform actions on behalf of the customer.

Apples to oranges.

Not having this will negatively impact conversion rates.

Seems like the only option at this moment in time is to try this multipass thing everyone is mentioning above, or maybe seeing if there is a way to implement [this](https://stackoverflow.com/questions/13432821/is-it-possible-to-add-request-headers-to-an-iframe-src-request) type of logic for injecting the X-Shopify-Customer-Access-Token: {customerAccessToken} as a header on an iFrame.

I may try both and update back if I get any luck.

Still really think Shopify should just let us pass a param.

**Comment by adrienpicard** [comment]
Facing this issue today too. Any update on implementing this into the Storefront API for non-Plug users @rebeccajfriedman?

**Comment by arslanramay** [comment]
> I’ve just realised that we can associate a shipping address to a checkout. Oh man. Not sure how I’ve missed that. That way the customer has no need to log in again as they’ll see their email address and shipping already prefilled. Awesome!

Looks like a good approach to associate shipping address to Checkout. However, I couldn't find any Mutation for associating **Shipping Address** to **Checkout** just like we have '**checkoutCustomerAssociateV2**'. Could you please provide some more detail about how did you associate Shipping Address to Checkout? Thanks! :)

**Comment by nboliver** [comment]
@arslanramay some forum posts suggest the use of `checkoutShippingAddressUpdateV2` to add the address, other Shopify docs imply you should log in with Multipass, but there are no examples of how to actually do that when you don't have a separate user system and just have a headless front end. Super frustrating!

**Comment by nboliver** [comment]
> I’ve just realised that we can associate a shipping address to a checkout. Oh man. Not sure how I’ve missed that. That way the customer has no need to log in again as they’ll see their email address and shipping already prefilled. Awesome!

But you can't do it with a cart, and you need to use the cart workflow to access subscriptions.
