### ISSUE TITLE
react-js-buy-sdk README code snippet needs to be updated

### ISSUE THREAD

**Issue by thiskevinwang** [Shopify/storefront-api-examples#89]
# Description 
The code snippet in the [react-js-buy-sdk README](https://github.com/Shopify/storefront-api-examples/blob/master/react-js-buy/README.md) needs to be updated.

It should match the contents of `src/index.js`

**Comment by swalkinshaw** [comment]
Closed by https://github.com/Shopify/storefront-api-examples/pull/88
