### ISSUE TITLE
Exposing Meta Fields to StoreFront API

### ISSUE THREAD

**Issue by skaltenegger** [Shopify/storefront-api-examples#94]
Dear Shopify tech team,

We saw that `metafields` and `metafield` have been added to your StoreFront API's GraphQL schema for the `Product` and `ProductVariant` type. When we query for those fields, we unfortunately still get an empty array or null as a result, even though the meta fields are set. See screenshot below:

<img width="1106" alt="Screenshot 2019-05-01 13 06 18" src="https://user-images.githubusercontent.com/7560151/57014822-09bb6d00-6c12-11e9-9ebd-cda96f99a350.png">

Do you have any idea of why this might happen in our case and if there is a way we can resolve this? We are using StoreFront GraphQL API for a large production build and would need this to work urgently, therefore very much appreciate your help here!

Thanks a lot and all the best,
Stefan

**Comment by rebeccajfriedman** [comment]
:wave: Metafields for Products and ProductVariants are indeed available through the Storefront API! [Follow the guide](https://help.shopify.com/en/api/custom-storefronts/storefront-api/guides/metafields) to learn more about how to get it up and running!

**Comment by pmourer** [comment]
@rebeccajfriedman are you sure about this? Is it only possible to access metafields that were created via graphql or something? I have a number of metafields that were created in admin via the bulk editor and custom apps and I am receiving the same response as shown above.

**Comment by pmourer** [comment]
It appears that they need to be "exposed" to the storefront API via the admin api (there does not seem to be any other way to do this?) and i did not see any mention of this anywhere. In my case, the query looked as such:
```
mutation {
  metafieldStorefrontVisibilityCreate(input: { namespace: "global", key: "short_description", ownerType: PRODUCT}) {
    userErrors {
      field
      message
    }
  }
}
```
