### ISSUE TITLE
But how are you meant to get a storefront-access-token?

### ISSUE THREAD

**Issue by eben3zer** [Shopify/storefront-api-examples#95]
Great react-js example, is quick and easy to integrate into my app. However.. How are you meant to get a storefront-access-token?

Do you have to go through the Oauth flow with a server side app or can you do it with postman?

**Comment by gil--** [comment]
You can create one under Private Apps on your store. It's a public token and does not require auth flow. https://help.shopify.com/en/api/custom-storefronts/storefront-api/getting-started#authentication

**Comment by eben3zer** [comment]
Yesss - this is what I was looking for - thank you!
